### ISSUE TITLE
Useless property checking for keys map

### ISSUE THREAD

**Issue by first-developer** [andrepolischuk/keycodes#1]
Hi, first thanks for this great library ;), it is really helpful.
While reading the codes, I found something that's look weird to me: https://github.com/andrepolischuk/keycodes/blob/master/index.js#L60-L64

Actually you're checking for each property of the `keys` object if it is a property of keys.
Is there any case where this checking could return false?

Thanks!

**Comment by andrepolischuk** [comment]
Hi, thanks.

If we don't use checking with `hasOwnProperty` `for...in` includes not only properties of `keys` but also properties of `Object.prototype`. It's not good in case if a third-party script will change the `Object.prototype`.

Example:

```js
var foo = {bar: true};
Object.prototype.baz = true;

for (var key in foo) {
  console.log(key); // bar, baz
}
```
