### ISSUE TITLE
ES6 modules support?

### ISSUE THREAD

**Issue by sbrl** [andrepolischuk/keycodes#3]
Support for ES6 modules would be great. Not sure how to support both at once, though.

**Comment by andrepolischuk** [comment]
fixed, please check master branch, will this solution suit your cases?

**Comment by sbrl** [comment]
Yep, that fixes it, @andrepolischuk! Thanks :D :smiley_cat:

**Comment by andrepolischuk** [comment]
published as v1.0.0
